version: "3.9"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mates
      MYSQL_USER: jhoans
      MYSQL_PASSWORD: jhoansPass
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    environment:
      MYSQLHOST: db
      MYSQLUSER: jhoans
      MYSQLPASSWORD: jhoansPass
      MYSQLDATABASE: mates
      MYSQLPORT: 3306
    volumes:
      - ./app:/app
      - ./db:/app/db
    ports:
      - "5000:5000"
    depends_on:
      - db
